### ISSUE TITLE
[QUESTION] Why smtpRequest is private ? 

### ISSUE THREAD

**Issue by plorgue** [truemail-rb/truemail-go#61]
### New question checklist

- [x] I have read the [Contribution Guidelines](https://github.com/truemail-rb/truemail-go/blob/master/CONTRIBUTING.md)
- [x] I have read the [documentation](https://truemail-rb.org/truemail-go)
- [x] I have searched for [existing GitHub issues](https://github.com/truemail-rb/truemail-go/issues)

### Question

It is not possible to easily access the content of `truemail.validatorResult.SmtpDebug` because the fields of `smtpRequest` are private. How to access easily to these fields ? 

I would like to know why smtp check fail by look at ` SmtpDebug[i].response`. Is that a choice to put those structs private ? 

Thanks for your work

**Comment by bestwebua** [comment]
Hello, @plorgue! Sorry for delay. Seems like `smtpRequest` should be exported structure with bunch of getters, and exported context of nested structures too. Good catch, thanks! I'll prepare some updates to fix this issue on the next week.

**Comment by bestwebua** [comment]
Hi, @plorgue! Sorry for delay. I have added ability to explore SMTP response erors: https://github.com/truemail-rb/truemail-go/pull/69 This feature is available in the latest `truemail-go` release. Cheers!
