### ISSUE TITLE
[ISSUE] Typographical error on line 49 in domain_list_match.go file

### ISSUE THREAD

**Issue by Double-DOS** [truemail-rb/truemail-go#76]
### New issue checklist

- [x] I have updated `truemail-go` to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/truemail-rb/truemail-go/blob/master/CONTRIBUTING.md)
- [x] I have read the [documentation](https://truemail-rb.org/truemail-go)
- [x] I have searched for [existing GitHub issues](https://github.com/truemail-rb/truemail-go/issues)

[ISSUE] Typographical error on line 49 in domain_list_match.go file

### Issue description
`// Returns true if whitelist validation enebled, otherwise returns false`
`func (validation *validationDomainListMatch) isWhitelistValidation() bool {`
`	validatorResult := validation.result`
`	return validatorResult.Configuration.WhitelistValidation`
`}`

As seen above, the comment reads Returns true if whitelist validation "enabled"
This is a typo, as the word should be "enabled"

**Comment by bestwebua** [comment]
Hi, @Double-DOS! Thank you so much for report. Done 🍺
