### ISSUE TITLE
[QUESTION] I am experiencing difficulties validating emails using the TrueMail API on my Local Ubuntu System

### ISSUE THREAD

**Issue by meharwaheed** [truemail-rb/truemail-go#88]
Hello Team,

I'm a PHP Laravel developer with no prior experience in Go. I've installed Go version **go1.21.6 on Linux/amd64**. I am looking to validate emails with **domain and MX** records using Go.

I've attempted to run **go build**, **go run .**, and **go run [specific files]**, but encountered various errors each time.

Could you please guide me through the necessary steps to run this validation process so that I can effectively validate emails?

Thank you.

**Comment by bestwebua** [comment]
@meharwaheed In this case I would recommend you just use truemail environment agnostic solution: https://truemail-rb.org/truemail-rack-docker-image
