### ISSUE TITLE
[QUESTION] Is it possible to do validation after the RCPT TO section in the SMTP session?

### ISSUE THREAD

**Issue by RichiMaulana** [truemail-rb/truemail-go#91]
### New question checklist

- [x] I have read the [Contribution Guidelines](https://github.com/truemail-rb/truemail-go/blob/master/CONTRIBUTING.md)
- [x] I have read the [documentation](https://truemail-rb.org/truemail-go)
- [x] I have searched for [existing GitHub issues](https://github.com/truemail-rb/truemail-go/issues)

### Question

When using Truemail as my main engine for validating emails I found that every time I validate Yahoo emails the results are always valid/true. After I try to debug the problems, turn out that Yahoo accepts all email addresses in the RCPT TO section, so even if the email doesn't exist the return from the Yahoo MX server will always be OK (250).  After I continued to the DATA section in the SMTP session the Yahoo MX server just returned the mailbox not exist message. 

Here is the detail:
```bash
$ swaks -s mta5.am0.yahoodns.net:25 -f richi@mukharom.my.id -t richisetyamaulanaaa@yahoo.com
=== Trying mta5.am0.yahoodns.net:25...
=== Connected to mta5.am0.yahoodns.net.
<-  220 mtaproxy511.free.mail.bf1.yahoo.com ESMTP ready
 -> EHLO vpndev.aktiva.co.id
<-  250-mtaproxy511.free.mail.bf1.yahoo.com
<-  250-PIPELINING
<-  250-SIZE 41943040
<-  250-8BITMIME
<-  250 STARTTLS
 -> MAIL FROM:<richi@mukharom.my.id>
<-  250 sender <richi@mukharom.my.id> ok
 -> RCPT TO:<richisetyamaulanaaa@yahoo.com>
<-  250 recipient <richisetyamaulanaaa@yahoo.com> ok
 -> DATA
<-  354 go ahead
 -> Date: Tue, 30 Apr 2024 04:24:03 +0000
 -> To: richisetyamaulanaaa@yahoo.com
 -> From: richi@mukharom.my.id
 -> Subject: test Tue, 30 Apr 2024 04:24:03 +0000
 -> Message-Id: <20240430042403.2835659@vpndev.aktiva.co.id>
 -> X-Mailer: swaks v20190914.0 jetmore.org/john/code/swaks/
 ->
 -> This is a test mailing
 ->
 ->
 -> .
<** 552 1 Requested mail action aborted, mailbox not found
 -> QUIT
*** Remote host closed connection unexpectedly.
```

So is there any workaround for this problem? I tried various validators that are available online and the result is valid.

Is the only way is just to do/continue the SMTP session until the DATA section? If it is, doesn't it will send the message to the target email if the email is valid?

**Comment by bestwebua** [comment]
Hi, @RichiMaulana! It could be... I guess for validating yahoo emails you should use another approach.
